version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: zhiqing_mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./ddl:/docker-entrypoint-initdb.d
    networks:
      - zhiqing_network_prod
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: zhiqing_redis_prod
    restart: unless-stopped
    volumes:
      - redis_data_prod:/data
    networks:
      - zhiqing_network_prod
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Django后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: zhiqing_backend_prod
    restart: unless-stopped
    environment:
      - DEBUG=False
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - mysql
      - redis
    networks:
      - zhiqing_network_prod
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Vue前端服务
  frontend:
    build:
      context: ./zhiqing_ui
      dockerfile: Dockerfile.prod
    container_name: zhiqing_frontend_prod
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - zhiqing_network_prod
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: zhiqing_nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - zhiqing_network_prod
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  mysql_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  zhiqing_network_prod:
    driver: bridge
