# Generated by Django 5.1.3 on 2025-08-27 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='敏感词')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='敏感级别')),
                ('replacement', models.CharField(default='***', max_length=100, verbose_name='替换词')),
                ('category', models.CharField(choices=[('general', '通用'), ('political', '政治'), ('business', '商业'), ('technical', '技术'), ('personal', '个人隐私'), ('other', '其他')], default='general', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sensitive_words', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sensitive_words', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'db_table': 'sensitive_words',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['level'], name='sensitive_w_level_6a1c7b_idx'), models.Index(fields=['category'], name='sensitive_w_categor_305138_idx'), models.Index(fields=['is_active'], name='sensitive_w_is_acti_dbcef3_idx'), models.Index(fields=['priority'], name='sensitive_w_priorit_97fe1a_idx'), models.Index(fields=['created_at'], name='sensitive_w_created_06e389_idx')],
            },
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='停用词')),
                ('language', models.CharField(choices=[('chinese', '中文'), ('english', '英文'), ('mixed', '混合')], default='chinese', max_length=10, verbose_name='语言类型')),
                ('category', models.CharField(choices=[('general', '通用'), ('technical', '技术'), ('academic', '学术'), ('business', '商业'), ('medical', '医疗'), ('legal', '法律'), ('other', '其他')], default='general', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stop_words', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stop_words', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '停用词',
                'verbose_name_plural': '停用词',
                'db_table': 'stop_words',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['language'], name='stop_words_languag_be471b_idx'), models.Index(fields=['category'], name='stop_words_categor_ab5120_idx'), models.Index(fields=['is_active'], name='stop_words_is_acti_e8baa1_idx'), models.Index(fields=['priority'], name='stop_words_priorit_0eeef3_idx'), models.Index(fields=['created_at'], name='stop_words_created_ddbc7b_idx')],
                'unique_together': {('word', 'language')},
            },
        ),
    ]
