# Generated by Django 5.1.3 on 2025-08-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('real_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role_id', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='sensitiveword',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sensitive_words', to='knowledge_mgt.customuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='sensitiveword',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sensitive_words', to='knowledge_mgt.customuser', verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='stopword',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stop_words', to='knowledge_mgt.customuser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='stopword',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stop_words', to='knowledge_mgt.customuser', verbose_name='更新人'),
        ),
    ]
