-- 文档上传任务表
CREATE TABLE IF NOT EXISTS `document_upload_task` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `task_id` varchar(64) NOT NULL COMMENT '任务唯一标识',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `database_id` bigint(20) NOT NULL COMMENT '知识库ID',
  `filename` varchar(255) NOT NULL COMMENT '文件名',
  `file_path` varchar(500) NOT NULL COMMENT '文件路径',
  `file_size` bigint(20) NOT NULL COMMENT '文件大小(字节)',
  `chunking_method` varchar(20) DEFAULT 'token' COMMENT '分块方法',
  `chunk_size` int(11) DEFAULT 500 COMMENT '分块大小',
  `similarity_threshold` decimal(3,2) DEFAULT 0.70 COMMENT '相似度阈值',
  `overlap_size` int(11) DEFAULT 100 COMMENT '重叠大小',
  `custom_delimiter` varchar(10) DEFAULT '\n\n' COMMENT '自定义分隔符',
  `window_size` int(11) DEFAULT 3 COMMENT '滑动窗口大小',
  `step_size` int(11) DEFAULT 1 COMMENT '步长',
  `min_chunk_size` int(11) DEFAULT 50 COMMENT '最小分块大小',
  `max_chunk_size` int(11) DEFAULT 2000 COMMENT '最大分块大小',
  `status` enum('pending','processing','completed','failed','cancelled') DEFAULT 'pending' COMMENT '任务状态',
  `progress` int(11) DEFAULT 0 COMMENT '处理进度(0-100)',
  `error_message` text COMMENT '错误信息',
  `chunk_count` int(11) DEFAULT 0 COMMENT '生成的分块数量',
  `document_id` bigint(20) DEFAULT NULL COMMENT '生成的文档ID',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `started_at` timestamp NULL DEFAULT NULL COMMENT '开始处理时间',
  `completed_at` timestamp NULL DEFAULT NULL COMMENT '完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_database_id` (`database_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档上传任务表';